spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # 密码 没有则可以不填
    password:
    #连接池超时时间（毫秒）
    timeout: 2000000
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大活跃链接数（使用负值表示没有限制）
        max-active: 500
        # 最大空闲连接数
        max-idle: 20
        # 最小空闲连接数
        min-idle: 10
        #连接池最大阻塞时间（使用负值表示没有限制）
        max-wait: -1
    # 数据库
    database: 0

qbk:
  config:
    redis:
      enabled: true