# 分布式文件系统FDFS配置
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  webServerUrl: http://39.106.33.10:8089/ # nginx 端口 默认是80  和nginx.conf 的listen 值对应
  thumb-image: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #部署fastdfs服务的机器ip和端口  端口默认为22122 每个服务器一行即可
    - 39.106.33.10:22122
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: 100
     #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数
    max-total-per-key: 50